services:
  web:
    build: .
    ports:
      - "3000:8080"
    environment:
      - DEBUG=True
      - VALUATION_API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8080

  api:
    build: ./api
    ports:
      - "3001:8000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONPATH=/app