services:
  django:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - DEBUG=True
      - VALUATION_API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ..:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8080

  api:
    build: ../api
    ports:
      - "8000:8000"
    volumes:
      - ../api:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app